sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t kevincoakley/ubuntu14.04-upstart-java ubuntu-java/14.04/

script:
    - docker run --detach --privileged --name ubuntu14.04-upstart-java kevincoakley/ubuntu14.04-upstart-java
    - bash ./tests/ubuntu_1404.sh

after_script:
    - docker ps -a
    - docker logs ubuntu16.04-systemd
